import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        th: {
          bg: "var(--bg)",
          surface: "var(--bg-surface)",
          hover: "var(--bg-hover)",
          inset: "var(--bg-inset)",
          overlay: "var(--bg-overlay)",
          text: "var(--text)",
          "text-2": "var(--text-2)",
          "text-3": "var(--text-3)",
          "text-4": "var(--text-4)",
          border: "var(--border)",
          "border-light": "var(--border-light)",
          accent: "var(--accent)",
          "accent-hover": "var(--accent-hover)",
          "accent-bg": "var(--accent-bg)",
          "accent-muted": "var(--accent-muted)",
          "accent-text": "var(--accent-text)",
          "accent-border": "var(--accent-border)",
          positive: "var(--positive)",
          "positive-bg": "var(--positive-bg)",
          "positive-border": "var(--positive-border)",
          "positive-text": "var(--positive-text)",
          "positive-bar": "var(--positive-bar)",
          negative: "var(--negative)",
          "negative-bg": "var(--negative-bg)",
          "negative-border": "var(--negative-border)",
          "negative-text": "var(--negative-text)",
          warning: "var(--warning)",
          "warning-bg": "var(--warning-bg)",
          "warning-border": "var(--warning-border)",
          "warning-text": "var(--warning-text)",
          "nav-active": "var(--nav-active)",
          "nav-active-text": "var(--nav-active-text)",
          skeleton: "var(--skeleton)",
          bar: "var(--bar-bg)",
          "tooltip-bg": "var(--tooltip-bg)",
          "tooltip-text": "var(--tooltip-text)",
          "focus-ring": "var(--focus-ring)",
          "focus-border": "var(--focus-border)",
          "score-high": "var(--score-high)",
          "score-mid": "var(--score-mid)",
          "score-low": "var(--score-low)",
          "score-vlow": "var(--score-vlow)",
          "score-high-bg": "var(--score-high-bg)",
          "score-mid-bg": "var(--score-mid-bg)",
          "score-low-bg": "var(--score-low-bg)",
          "score-vlow-bg": "var(--score-vlow-bg)",
        },
      },
    },
  },
  plugins: [],
};
export default config;
